### ISSUE TITLE
Opening a single empty file using format auto-detect raises OSError.

### ISSUE THREAD

**Issue by DriesSchaumont** [marcelm/dnaio#3]
Hi,

I have recently stumbled into an error trying to open an empty file that does not have a regular extension (fasta, fastq,...), by using open with auto-detect (fileformat=None).  Quick example:

```
$ python3 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install dnaio
Collecting dnaio
  Using cached dnaio-0.4.2-cp38-cp38-manylinux1_x86_64.whl (126 kB)
Collecting xopen>=0.8.2
  Using cached xopen-0.9.0-py2.py3-none-any.whl (8.3 kB)
Installing collected packages: xopen, dnaio
Successfully installed dnaio-0.4.2 xopen-0.9.0
(.venv) $ python3
python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dnaio
>>> import pathlib
>>> pathlib.Path('test.tmp').touch()
>>> dnaio.open('test.tmp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.8/site-packages/dnaio/__init__.py", line 108, in open
    return _open_single(
  File ".venv/lib/python3.8/site-packages/dnaio/__init__.py", line 177, in _open_single
    fileformat = _detect_format_from_content(file)
  File ".venv/lib/python3.8/site-packages/dnaio/__init__.py", line 203, in _detect_format_from_content
    file.seek(-1, 1)
OSError: [Errno 22] Invalid argument
>>> dnaio.open('test.tmp', fileformat='Fasta')
<dnaio.readers.FastaReader object at 0x7f0910594880>
```

I understand that in this case it is not possible to infer a file type, but I would like to suggest to use a more detailed error message to explain what is going on.

Thank you for your time!
Dries

**Comment by marcelm** [comment]
Thanks so much for reporting this! And sorry for the delay, I have been away from work for quite a while.

I have fixed the problem now (the library will detect empty files as FASTQ) and added a unit test so that it doesn’t occur again.
